ignored:
  - DL3018
  - DL3025
  - DL3008
  - DL4006
  - DL3003
  - DL3015
  - SC2086
  - SC1091
  - DL4001
  - SC2046

trustedRegistries:
  - docker.io
  - core-harbor.us-east-2.codefi.network/staking